-- 1. Create the Applications Table
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref TEXT UNIQUE NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT DEFAULT 'Pending',

    -- Section 1: Personal Info
    full_name TEXT NOT NULL,
    date_of_birth DATE NOT NULL,
    place_of_birth TEXT NOT NULL,
    nationality TEXT NOT NULL,
    marital_status TEXT NOT NULL,
    address TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,

    -- Section 2: Family & Professional
    dependent_children INTEGER DEFAULT 0,
    profession TEXT NOT NULL,
    employer TEXT NOT NULL,
    income NUMERIC DEFAULT 0,
    housing_type TEXT NOT NULL,

    -- Section 3: Adoption Project
    motivation TEXT NOT NULL,
    adoption_type TEXT NOT NULL,
    preferred_age TEXT NOT NULL,
    preferred_gender TEXT,
    preferred_country TEXT,
    special_needs TEXT DEFAULT 'no',
    special_needs_details TEXT,

    -- Section 5: Declaration
    signature TEXT NOT NULL,
    signature_date DATE NOT NULL,

    -- Documents (Supabase Storage public URLs)
    doc_identity TEXT,
    doc_proof_address TEXT,
    doc_financial TEXT
);

-- 2. Enable Row Level Security
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for the applications table
-- The Node backend uses the service_role key which bypasses RLS.
-- These policies are a safety net in case the anon key is used by mistake.

-- No public read access
CREATE POLICY "Service role full access"
    ON public.applications
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- 4. Create the Storage Bucket for Documents
INSERT INTO storage.buckets (id, name, public)
VALUES ('applications_docs', 'applications_docs', true);

-- 5. Storage Security Policies
-- Allow public access to view files (admin panel loads public URLs)
CREATE POLICY "Public Access"
    ON storage.objects FOR SELECT
    USING ( bucket_id = 'applications_docs' );

-- Allow service role to upload files
CREATE POLICY "Allow Uploads"
    ON storage.objects FOR INSERT
    WITH CHECK ( bucket_id = 'applications_docs' );

-- Allow service role to delete files (admin panel feature)
CREATE POLICY "Allow Deletes"
    ON storage.objects FOR DELETE
    USING ( bucket_id = 'applications_docs' );
